blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts")),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

posts/urls.py
from django.urls import path
from posts import views
from posts.views import subscribe


app_name = "posts"


urlpatterns = [
    path("subscribe/<int:id>/",subscribe,name="subscribe")
]

users/urls.py
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

web/urls.py
from django.urls import path
from web import views


app_name = "web"


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.post, name='post'),
    
]

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

# from django.contrib.auth impor 

class Owner(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    featured_image = models.ImageField(upload_to="posts/")
    image1 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    image2 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    image3 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    image4 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    price = models.IntegerField()
    is_draft = models.BooleanField(default=False)
    district = models.CharField(max_length=255)
    owner = models.ForeignKey("posts.Owner", on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Subscribe(models.Model):
    user = models.ForeignKey("posts.Owner", on_delete=models.CASCADE)
    post = models.ForeignKey("posts.Post", on_delete=models.CASCADE)
    email=models.EmailField(max_length=254)
    book_date = models.DateField()

    def __str__(self):
        return self.email

posts/forms.py
from django import forms
from posts.models import Post
from posts.models import Subscribe


class PostForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': "input"}), label="Tags (Comma separated)")

    class Meta:
        model = Post
        exclude = ('author', 'published_date', 'category')

        widgets = {
            "title" : forms.TextInput(attrs={'class': "input"}),
            "short_description" : forms.Textarea(attrs={'class': "input"})
        }

        error_messages = {
            "title" : {
                "required": "Title field is required"
            },
            "short_description" : {
                "required": "Short description field is required"
            },
            "tags" : {
                "required": "Tag field is required"
            },
            "featured_image" : {
                "required": "Featured image field is required"
            },
            "categories" : {
                "required": "Draft field is required"
            },
            "author" : {
                "required": "author field is required"
            },
            "published_date" : {
                "required": "published_date field is required"
            }, 
           
        }

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ('email','book_date')

        widgets = {
            "book_date" : forms.TextInput(attrs={'type':'date'}),
        }

posts/views.py
import json
import datetime

from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

from posts.forms import PostForm
from posts.models import Owner, Category, Post, Subscribe
from main.functions import generate_form_error, paginate_instances
from main.decorators import allow_self


@login_required(login_url="/users/login/")
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():

            tags = form.cleaned_data['tags']

            if not Owner.objects.filter(user=request.user).exists():
                owner = Owner.objects.create(user=request.user, name=request.user.username)
            else:
                owner = request.user.owner


            instance = form.save(commit=False)
            instance.published_date = datetime.date.today()
            instance.owner= owner
            instance.save()

            tags_list = tags.split(",")
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.category.add(category)

            response_data ={
                "title" : "Succefully created",
                "message" : "Succefully Created",
                "status" : "success",
                "redirect" : "yes",
                "redirect_url" : "/"

            }

        else:
            error_message = generate_form_error(form)
            response_data = {
                "title" : "From validation error",
                "message" : str(error_message),
                "status" : "error",
                "stable" : "yes",

            }
        return HttpResponse(json.dumps(response_data), content_type="application/json")   

    else:
        form = PostForm()
        context = {
            "title" : "Create new Post",
            "form" : form,
        }
        return render(request, "posts/create.html", context=context)


@login_required(login_url="/users/login/")
def my_posts(request):
    posts = Post.objects.filter(owner__user=request.user, is_deleted=False)
    instances = paginate_instances(request, posts, per_page=1)
    context = {
        "title" : "Blog | My Post",
        "instances" : instances
    }
    return render(request, "posts/my-posts.html", context=context)


@login_required(login_url="/users/login/")
@allow_self
def delete_post(request, id):
    instance = get_object_or_404(Post, id=id)
    instance.save()

    reponse_data = {
        "title" : "Succefully deleted",
        "message" : "Post Deleted successfully",
        "status" : "success",
    }

    return HttpResponse(json.dumps(reponse_data), content_type="application/json")


@login_required(login_url="/users/login/")
@allow_self
def draft_post(request, id):
    instance = get_object_or_404(Post, id=id)
    instance.save()

    reponse_data = {
        "title" : "Succefully Changed",
        "message" : "Post Updated successfully",
        "status" : "success",
    }

    return HttpResponse(json.dumps(reponse_data), content_type="application/json")

 
@login_required(login_url="/users/login/")
@allow_self
def edit_post(request, id):
    instance = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():

            tags = form.cleaned_data['tags']

            instance = form.save(commit=False)
            instance.save()

            instance.category.clear()

            tags_list = tags.split(",")
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.category.add(category)

            response_data ={
                "title" : "Succefully created",
                "message" : "Succefully Created",
                "status" : "success",
                "redirect" : "yes",
                "redirect_url" : "/"

            }  

        else:
            error_message = generate_form_error(form)
            response_data = {
                "title" : "From validation error",
                "message" : str(error_message),
                "status" : "error",
                "stable" : "yes",

            }
        return HttpResponse(json.dumps(response_data), content_type="application/json")     

    else:
        category_string = ""
        for category in instance.category.all():
            category_string += f"{category.title},"

        form = PostForm(instance=instance, initial={"tags" : category_string[:-1]})
        context = {
            "title" : "Create new Post",
            "form" : form,
        }
        return render(request, "posts/create.html", context=context)


@login_required(login_url="/users/login/")
def subscribe(request, id):
    user = request.user

    email = request.POST.get("email")
    book_date = request.POST.get("book_date")

    if Post.objects.filter(id=id).exists():
        print(Subscribe.book_date)
        owner = Owner.objects.get(user=user)

        post = Post.objects.get(id=id)

        sub = Subscribe.objects.all()
        
        book = False
        for s in sub:
            print(s.book_date, '========', book_date)
            str_sub_book_date = str(s.book_date)
            str_book_date = str(book_date)
            print(str_sub_book_date == str_book_date)

            if str_sub_book_date == str_book_date:
                sub_post_title = s.post.title
                # print(s.post.filter(title=sub_post_title).exists(), "postlkjdsafkuhdsiu")
                # print(, 'title')
                # print(sub_post_title)
                if s.post.title == post.title:
                    print("hello")
                    book = False
                    print('break')
                    break
                    response_data = {
                            "title" : "Already booked",
                            "status" : "Error",
                            "stable" : "yes",
                        }

                    return HttpResponse(json.dumps(response_data), content_type="application/json") 
                else:
                    book = True
            else:
                    book = True
                

        print(book, "++++++++++++=")

        if book:
            post = Post.objects.get(id=id)
            Subscribe.objects.create(
                                email=email,
                                book_date=book_date,
                                post=post,
                                user=owner
                            )

            response_data = {
                                    "title" : "Successfully Booked",
                                    "status" : "success",
                                    "stable" : "yes",
                                }
            return HttpResponse(json.dumps(response_data), content_type="application/json")
        else:
            response_data = {
                            "title" : "Already booked",
                            "status" : "Error",
                            "stable" : "yes",
                        }

            return HttpResponse(json.dumps(response_data), content_type="application/json")        
    else:
        response_data = {
                "title" : "This post doesn't exists",
                "status" : "Error",
                "stable" : "yes",

            }
        return HttpResponse(json.dumps(response_data), content_type="application/json") 

templates/web/index.html
{% extends "base.html" %} {% block content %} {% load static %}
{% load paginator_tags %}
<section id="home">
  <section class="wrapper">
    {% include 'web/includes/header.html' %}
    <section class="spotlight">
      <div class="bc">
        <h1>EVENT . </h1>
        <p>WE ARE HERE TO PROVIDE THE BEST</p>
      </div>
      <div class="about">
        <h2>About Us</h2>
        <p>Welcome to Event ., the premier event management website for all your special occasions. Our team of experienced professionals is dedicated to providing top-notch event planning, coordination, and execution services to ensure that your event is a success. Whether it's a corporate conference, a wedding, or a birthday party, we work with you every step of the way to make your vision a reality. With our attention to detail and commitment to excellence, you can trust us to handle all the logistics so that</br><b>you can sit back, relax, and enjoy your event.</b> </p>
          <img src="{% static './images/event10.jpeg' %}" alt="" />
      </div>
      <div class="gallery">
        <div class="top"><h2>Event Memories</h2></div>
        <div class="bottom"></div>
        <img src="{% static './images/event.jpg' %}" alt="image1" />
        <img src="{% static './images/mem1.jpeg' %}" alt="image1" />
        <img src="{% static './images/mem2.jpeg' %}" alt="image1" />
        <img src="{% static './images/mem3.jpeg' %}" alt="image1" />
        <img src="{% static './images/mem4.jpeg' %}" alt="image1" />
        <img src="{% static './images/mem5.jpeg' %}" alt="image1" />
        <img src="{% static './images/mem2.jpeg' %}" alt="image1" />
        <img src="{% static './images/mem1.jpeg' %}" alt="image1" />
      </div>
      <centre>
      <div class="reviews">
        <div class="board">
            <h2 class="text-light">Word form our customers</h2>
            <p class="text-light">Some of the fullfilled costomers reviews</p>

            <!-- Slider main container -->
            <div class="swiper">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                <!-- Slides -->
                <div class="swiper-slide">
                    <div class="flex">
                        <div class="comments">
                          This event management website was a lifesaver! The user-friendly interface, responsive customer service, and top-notch event planning tools made organizing my conference a breeze. Highly recommend!"
                        </div>
                        <div class="profile">
                            <img src="https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60" alt="">
                            <a href="#">Sita Mahalakshmi</a>
                            <span>happy customer</span>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="flex">
                        <div class="comments">
                          Using this event management website was a game-changer. The intuitive platform, helpful customer support, and excellent event planning tools allowed me to host a successful and stress-free event. Highly recommended!
                         </div>
                        <div class="profile">
                            <img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60" alt="">
                            <a href="#">Mrunal thakur</a>
                            <span>happy customer</span>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="flex">
                        <div class="comments">
                          Event. is the ultimate event management website! From planning to execution, their team of experts seamlessly handle every aspect of your event
                        </div>
                        <div class="profile">
                            <img src="https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60" alt="">
                            <a href="#">Princes Noorjahan</a>
                            <span>happy customer</span>
                        </div>
                    </div>
                </div>
                </div>
                <!-- If we need pagination -->
                <div class="swiper-pagination"></div>
            
                <!-- If we need navigation buttons -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
        
            </div>

        </div>
    </div>
      <center> 
      <h3 style="font-size: 35px;">Event Teams</h3>
    </center>
      <div class="filtersection" id="hamburger-menu">
        <form action="">
          <input type="text" name="q" placeholder="Search your event team..." />
        </form>
      </div>
      <div class="all-posts">
        <div class="post-section">
          <ul class="posts">
            {% for post in instances %}
            <li>
              {% if request.user.is_authenticated %}
              <a href="{% url 'web:post' id=post.id %}">
              {% else %}
              <a href="{% url 'users:login' %}" class="login">
              {% endif %}
                <div class="blog-image">
                  <img src="{{post.featured_image.url}}" alt="Blog" />
                </div>
                <div class="details">
                  <div class="date">
                    <h4 class="name">{{post.author.name}}</h4>
                  <h3 class="head">{{post.title}}</h3>
            </li>
            {% endfor %}
          </ul>
          {% load_pagination instances %}
        </div>
      </div>
    </section>
    <div id="overlay"></div>
    <div id="close">
      <img src="{% static './images/icons/close.svg' %}" alt="" />
    </div>
  </section>
</section>
{% endblock %}

templates/web/post.html
{% extends "base.html" %} {% block content %} {% load static %}
    <section id="single-page-home">
        <section class="wrapper">         
           {% include 'web/includes/header.html' %}
            <section class="single-page-spotlight">
                <h3 class="title">
                    {{instances.title}}
                </h3>
                <p class="description">
                    {{instances.short_description}}
                </p>
                <h2>Location : {{instances.district}} </h2><br><br>
                <div class="post-thumbnail">
                    <img src="{{instances.featured_image.url}}" alt="Post-thumbnail" >
                </div>
                <div class="gallery1">
                    <div class="top"><h2>Our Works</h2></div>
                    <div class="bottom">
                    <img src="{{instances.image1.url}}" alt="image1" />
                    <img src="{{instances.image2.url}}" alt="image2" />
                    <img src="{{instances.image3.url}}" alt="image3" />
                    <img src="{{instances.image4.url}}" alt="image4" />
                    </div>
                </div>
                <section class="service" id="service">

                    <h1 class="heading"> our <span>services</span> </h1>
                
                    <div class="box-container">
                
                        <div class="box">
                            <i class="fas fa-map-marker-alt"></i>
                            <h3>venue selection</h3>
                            <p>Venue selection is a critical aspect of event management,
                                as it can impact the success of the event.
                                Factors such as location, capacity, amenities, and cost must be considered
                                in order to choose the best venue that meets the needs and objectives of the event.</p>
                        </div>
                
                        <div class="box">
                            <i class="fas fa-envelope"></i>
                            <h3>invitation card</h3>
                            <p>Invitation cards are an essential element of event management,
                                as they convey important information and set the tone for the event.
                                The design, wording, and format of the invitation card must be carefully crafted
                                to reflect the style and purpose of the event, and to make a lasting impression on the guests./p>
                        </div>
                
                        <div class="box">
                            <i class="fas fa-music"></i>
                            <h3>entertainment</h3>
                            <p>Entertainment is a key component of event management,
                                as it can help create a memorable and enjoyable experience for attendees.
                                The type of entertainment chosen must align with the theme and audience of the event,
                                and can include live music, performers, games, or interactive activities.</p>
                        </div>
                
                        <div class="box">
                            <i class="fas fa-utensils"></i>
                            <h3>food and drinks</h3>
                            <p>Food and drinks are an important aspect of event management,
                                as they can greatly enhance the guest experience and satisfaction.
                                The menu should be carefully planned to accommodate any dietary restrictions,
                                and the presentation and quality of the food and drinks should be top-notch to leave a lasting impression.</p>
                        </div>
                
                        <div class="box">
                            <i class="fas fa-photo-video"></i>
                            <h3>photos and videos</h3>
                            <p>Photos and videos are a crucial part of event management,
                                as they capture the highlights and essence of the event for future reference.
                                Professional photographers and videographers can be hired to capture the event,
                                and the resulting footage can be used for marketing, social media, and as a memento for attendees..</p>
                        </div>
                
                        <div class="box">
                            <i class="fas fa-birthday-cake"></i>
                            <h3>custom food</h3>
                            <p>Custom food is a unique and personalized aspect of event management,
                                which can be tailored to the specific needs and preferences of the event and its attendees..</p>
                        </div>
                
                    </div>
                
                </section>
                <section class="price" id="price">

                    <h1 class="heading"> our <span>price</span> </h1>
                
                    <div class="box-container">
                
                        <div class="box">
                            <h3 class="title">Celebration starts here</h3>
                            <h3 class="amount">₹{{instances.price}}</h3>
                            <ul>
                                <li><i class="fas fa-check"></i>full services</li>
                                <li> <i class="fas fa-check"></i> decorations </li>
                                <li> <i class="fas fa-check"></i> music and photos </li>
                                <li> <i class="fas fa-check"></i> food and drinks </li>
                                <li> <i class="fas fa-check"></i> invitation card </li>
                            </ul>
                        </div>

                    </div>
                    </section>
                
                
                <div class="details">
                    <ul class="social">
                        <li class="social-media">
                            <a target="_blank" href="https://twitter.com/intent/tweet?text={{request.build_absolute_url}}">
                                <img src="{% static 'images/icons/twitter.svg' %}" alt="Twitter" />
                            </a>
                        </li>

                        <li class="social-media">
                            <a target="_blank" href="https://www.facebook.com/sharer.php?u={{request.build_absolute_url}}">
                                <img src="{% static 'images/icons/facebook.svg' %}" alt="Facebook" />
                            </a>
                        </li>
                        <li class="social-media">
                            <a target="_blank" href="https://api.whatsapp.com/send/?text={{request.build_absolute_url}}">
                                <img src="{% static 'images/icons/whatsapp.svg' %}" alt="Linked-in" />
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <div class="form">
                    <form action="{% url 'posts:subscribe' id=instances.id  %}" method="post" class="ajax reload" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                          <label for="{{subscribe.email.id_for_label}}" class="subheads" >
                            {{subscribe.email.label}}
                        </label>
                          {{subscribe.email}}
                          <label for="{{subscribe.book_date.id_for_label}}" class="subheads" >
                            {{subscribe.book_date.label}}
                        </label>
                          {{subscribe.book_date}}
                        </div>
                        
                        <button id="book-event-button" type="submit">Book your event</button>
                        <!-- <script>
                            document.getElementById("book-event-button").addEventListener("click",function(){
                            alert("Successfully booked your event")
                         });
                        </script> -->
                      </form>
                      <h1>Already booked Dates</h1>
                      {% for dates in date %}
                      <h1>{{dates.post.title}},{{dates.book_date}}</h1>
                      <h1></h1>
                      <!-- <h1>{{dates.email}}</h1> -->
                      {% endfor %}
                    </div>
                </div>
                </section>
        </section>
    </section>

{% endblock %}