blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts")),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

users/urls.py
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

web/urls.py
from django.urls import path
from web import views


app_name = "web"


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.post, name='post'),
    
]

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

# from django.contrib.auth impor 

class Owner(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    featured_image = models.ImageField(upload_to="posts/")
    image1 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    image2 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    image3 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    image4 = models.ImageField(upload_to='posts/', null=True, blank=True, default='default.jpg')
    price = models.IntegerField()
    is_draft = models.BooleanField(default=False)
    district = models.CharField(max_length=255)
    owner = models.ForeignKey("posts.Owner", on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Subscribe(models.Model):
    user = models.ForeignKey("posts.Owner", on_delete=models.CASCADE)
    post = models.ForeignKey("posts.Post", on_delete=models.CASCADE)
    email=models.EmailField(max_length=254)
    book_date = models.DateField()

    def __str__(self):
        return self.email

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password"]
        widgets = {
            "password" : forms.widgets.PasswordInput()
        }

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User

from users.forms import UserForm
from main.functions import generate_form_error
from posts.models import Owner


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)

                return HttpResponseRedirect("/")
        
        context = {
            "title" : "Login",
            "error" : True,
            "message" : "Invalid username or password"
        }
        return render(request, 'users/login.html', context=context)    
    context = {
        "title" : "Login",
    }
    return render(request, 'users/login.html', context=context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username=instance.username,
                password=instance.password,
                email=instance.email,
                first_name=instance.first_name,
                last_name = instance.last_name,
            )

            Owner.objects.create(name=instance.first_name, user=user)

            user = authenticate(request, username=instance.username, password=instance.password)
            auth_login(request, user)

            return HttpResponseRedirect(reverse("web:index"))
        else:
            message = generate_form_error(form)

            form = UserForm()
            context = {
                "title" : "Signup",
                "error" : True,
                "message" : message,
                "form": form,
            }
        return render(request, 'users/signup.html', context=context)    

    else:
        form = UserForm()
        context = {
             "title" : "Signup",
             "form": form,
        }
        return render(request, 'users/signup.html', context=context)

templates/users/auth_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
            name="viewport"
            content="width=<device-width>, initial-scale=1.0"
        />

        <link rel="stylesheet" href="{% static './css/auth-style.css' %}" />

        <title>Signup</title>
    </head>
    <body>
        <section class="container">
            {% block content %} {% endblock %}
        </section>
    </body>
</html>

templates/users/login.html
{% extends "users/auth_base.html" %} {% block content %} {% load static %}
<section class="form_container">
  <div class="top">
    <h5>Login Page</h5>
  </div>
  <div class="bottom">
    <form action="" method="post">
      {% csrf_token %}
      <div class="input_container">
        <label for="id_username"> Username </label>
        <input id="id_username" name="username" type="text" />
      </div>
      <div class="input_container">
        <label for="id_password"> Password </label>
        <input id="id_password" name="password" type="password" />
      </div>
      <div class="submit_container">
        {% if error %}
        <p class="error-message">{{message}}</p>
        {% endif %}
        <button type="submit">Log in</button>

        <a href="{% url 'users:signup' %}">Create Account</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/users/signup.html
{% extends "users/auth_base.html" %} {% block content %} {% load static %}

<section class="form_container">
  <div class="top">
    <h5>Login Page</h5>
  </div>
  <div class="bottom">
    <form action="" method="post">
        {% csrf_token %}
      <div class="input_container">
        <label for="id_first_name"> First name </label>
        <input
          type="text"
          name="first_name"
          maxlength="150"
          id="id_first_name"
        />
      </div>

      <div class="input_container">
        <label for="id_last_name"> Last name </label>
        <input type="text" name="last_name" maxlength="150" id="id_last_name" />
      </div>

      <div class="input_container">
        <label for="id_email"> Email address </label>
        <input type="email" name="email" maxlength="254" id="id_email" />
      </div>
      <div class="input_container">
        <label for="id_phone"> Mobile Number </label>
        <input type="phone" name="phone" maxlength="254" id="id_phone" />
      </div>

      <div class="input_container">
        <label for="id_username"> Username </label>
        <input
          type="text"
          name="username"
          maxlength="150"
          required
          id="id_username"
        />
      </div>

      <div class="input_container">
        <label for="id_password"> Password </label>
        <input
          type="password"
          name="password"
          class="hello hi"
          placeholder="Enter strong password"
          maxlength="128"
          required
          id="id_password"
        />
      </div>

      <div class="submit_container">
        {% if error %}
        <p class="error-message">{{message}}</p>
        {% endif %}
        <button type="submit">Create Account</button>

        <a href="{% url 'users:login' %}">Login</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}